@rootAPI = http://localhost:8001


############ Categories ########

### Fetching all categories
GET {{rootAPI}}/categories




############# Products ########
GET {{rootAPI}}/products


### Fetching all products based on category ID
GET {{rootAPI}}/products/categories/summer-clothings/64d823f2c73b765ae5b018e5


### Find product by slug
GET {{rootAPI}}/products/product/albany-casual-shirt


#=========== Admin API

### Create new user
POST {{rootAPI}}/user
Content-Type: application/json

{
    "fname":"Bijay",
     "lname":"Nagarkoti",
     "phone":"0410584026",
     "email":"nagardafdfkoti@gmail.com",
     "password":"aaaaaaaa",
     "profileImg":"afdafjd.jpg"
}
