@rootAPI = http://localhost:8001


############ Categories ########

### Fetching all categories
GET {{rootAPI}}/categories




############# Products ########
GET {{rootAPI}}/products


### Fetching all products based on category ID
GET {{rootAPI}}/categories/summer-clothings/64d823f2c73b765ae5b018e5


### Find product by slug
GET {{rootAPI}}/product/joggers